### ISSUE TITLE
Restore ability to store encrypted secrets in a database.

### ISSUE THREAD

**Issue by joostd** [SURFnet/oath-service-php#6]
The original tiqr-server-lib had a way to encrypt secrets when stored in a database. 
oath-service-php can choose to use a YubiHSM for storing secrets securely, or simply store secrets in a database. In the latter case, the ability to store encrypted secrets seems to have been lost. 

Please restore the ability to store encrypted secrets, such that a shared, non-local database can be used for storing tiqr secrets by configuring an encryption key.

**Comment by lineke** [comment]
Fixed by implementing openssl. PR is merged and can be tested now.
